### ISSUE TITLE
Doesn't support ES6 generators?

### ISSUE THREAD

**Issue by romu70** [fdecampredon/brackets-eslint#2]
Hi,
I'm totally new to web, Js, ES6, etc...I'm trying to code some app using [Koa](https://github.com/koajs/koa) which heavily uses ES6 generators. Code example:

```
app.use(function *() {  
// bla bla bla
});
```

ESLint report this error: `Unexpected token * app.use(function *() {`

**Comment by fdecampredon** [comment]
what is your .eslintrc configuration ?

**Comment by romu70** [comment]
Right now? I've no .eslintrc file, sorry...my web dev fluency :-D Should I
have one? I'll be able to continue this discussion only next week now.
Merry Christmas.

**Comment by romu70** [comment]
Hi, I'm closing the issue. I give up with Brackets, so it wouldn't be faire to take your time on this issue. Thanks for the help.
