### ISSUE TITLE
cannot handle ArrowFunctionExpression

### ISSUE THREAD

**Issue by Listor** [fdecampredon/brackets-eslint#6]
hey there,

when i add the rule 

```
        "require-jsdoc": [1, {
            "require": {
                "FunctionDeclaration": true,
                "MethodDefinition": true,
                "ClassDeclaration": true,
                "ArrowFunctionExpression": false
            }
        }]
```

to my eslintrc it says _data["1"].require.ArrowFunctionExpression" has additional properties_

maybe you can update the eslint version to a more recent one ?

Best,
Michael

**Comment by fdecampredon** [comment]
Hello,
Like I said in the readme, I don't use brackets anymore, and I don't want to maintain this extension anymore :).
However, if you make a pull-request for an updated eslint version I'd gladly accept it :).

**Comment by Listor** [comment]
ah sorry missed that part. will check if i can make a pull request. thx for the quick reply
